### PR TITLE
Add new Favorite Stops feature

### PR DESCRIPTION
**Pull request by evansobkowicz**
This web app is great, thank you for your work on it!

As a daily user of realtimerail, I've been wishing I could favorite stops for easy access without scrolling through the list of stops in a line. I saw this was also a desired feature in this issue https://github.com/jamespfennell/realtimerail.nyc-react/issues/39, and have implemented it in this pull request. 

Please feel free to let me know if you would rather not add this, or would like any changes -- happy to iterate! 

**Screenshots**

Homepage, no favorites:
Screenshot 2023-11-18 at 5 39 56 PM

Homepage, with favorites:
Screenshot 2023-11-18 at 5 38 03 PM

Stop page, default state:
Screenshot 2023-11-18 at 5 38 26 PM

Stop page, favorited:
Screenshot 2023-11-18 at 5 38 17 PM

### CODE REVIEW

**Comment by jamespfennell** [comment]
Awesome, thank you so much for taking this on! This is a great feature.

I have two UI suggestions/comments:

1. In the home page, how would you feel about putting the favorite stops behind a drop down, like how alerts are initially hidden when you open the route page? Or even having the favorites be on their own page, with a prominent link on top of the homepage? There are two motivations for this:
   1. Even if there are no favorites you could still have text like "No favorite stops" and then the drop down/new page could have text "add favorites by clicking the star next to a stop". This would make the feature more discoverable.
   2. Making it fast to get to non-favorites stops via the usual flow would still be nice.

1. Nit: on the stop page, would it be possible to tweak the margins so that the star is directly to the right of the stop name?

**Comment by jamespfennell** [comment]
Three more tiny comments :)

1. Instead of adding a new SVG, any thoughts on using the Unicode characters ★ and ☆?
1. My understanding is that this doesn't use cookies? Just want to double check the "No cookies, no tracking, no ads" claim in the footer is still honest.
1. Feel free to update the LICENSE file to be `Copyright (c) 2019-present realtimerail.nyc contributors`. But I can also do this as a follow-up.

**Comment by evansobkowicz** [comment]
Thanks for the quick feedback! I will work on addressing this and follow up in the next week or so.

> My understanding is that this doesn't use cookies? Just want to double check the "No cookies, no tracking, no ads" claim in the footer is still honest.

Yes, it uses the browser localstorage api which is different from cookies. All it stores it the stop Ids you've favorited in an array.

**Comment by evansobkowicz** [comment]
I've updated this with the following changes:

1. New /favorites page with an educational empty state
2. New navigation links list at the top of the homepage (I avoided adding new headings here, but let me know if you think this needs a different sort of styling)
3. Updated LICENSE
4. Switched to unicode character for favorite button
5. Moved favorite button next to stop title

**Updated screenshots:**

Home Page:
Screenshot 2023-12-02 at 12 25 55 PM

Stop Page:
Screenshot 2023-12-02 at 12 26 17 PM
Screenshot 2023-12-02 at 12 26 24 PM

Favorites Page:
Screenshot 2023-12-02 at 12 25 44 PM
Screenshot 2023-12-02 at 12 27 11 PM

**Comment by jamespfennell** [comment]
Thank you for the second round of changes! I'm going to merge it in now. Thank you for implementing this features - it's great!

One heads up is that if I add the "find stops by location" feature I may tweak the UI of the homepage. I think it would be nice to replace the current "realtimerail.nyc" banner with "Home | Favorites | Location" (with icons). As of now this is great though.

**Comment by jamespfennell** [comment]
It's live on the website now!

**Comment by evansobkowicz** [comment]
Awesome, thanks for adding this! And yeah, absolutely no worries if you modify or change this feature in the future!

**Pull request merged**
